### ISSUE TITLE
Add Installation Guide for MacOS 

### ISSUE THREAD

**Issue by thesauravkarmakar** [thesauravkarmakar/GitHub101#1]

**Comment by fedGL** [comment]
I don't mind helping!

**Comment by thesauravkarmakar** [comment]
> I don't mind helping!

Sure!

**Comment by thesauravkarmakar** [comment]
@fedGL Do you think separate files for Installation would be good for each OS?

**Comment by fedGL** [comment]
It would probably make it easier to read, otherwise the file will be very long, right?

**Comment by thesauravkarmakar** [comment]
> It would probably make it easier to read, otherwise the file will be very long, right?

Would you want to restructure it?

**Comment by fedGL** [comment]
Sure!

**Comment by thesauravkarmakar** [comment]
> Sure!

Check out issue #4. Message there, so I can assign you!

**Comment by thesauravkarmakar** [comment]
This issue is fixed #3 by @fedGL
