### ISSUE TITLE
Simple introduction to the GitHub CLI?

### ISSUE THREAD

**Issue by MM-coder** [thesauravkarmakar/GitHub101#10]
Github has this new CLI, could I write a simple introduction to getting it up and running?

**Comment by thesauravkarmakar** [comment]
> Github has this new CLI, could I write a simple introduction to getting it up and running?

Sure! Add some screenshots to it. Also star this project! :)

**Comment by thesauravkarmakar** [comment]
@MM-coder Fix the breaking of images. Also, add this CLI Installation in Installation folder 
![image](https://user-images.githubusercontent.com/48858582/95022110-c67ced80-0692-11eb-81e8-d2c60d34bf55.png)

**Comment by thesauravkarmakar** [comment]
@Justobioma Do you want to fix these issues and add proper images?

**Comment by Justobioma** [comment]
Hi @thesauravkarmakar. Sure if you let me, I can give it a try. Thanks
