### ISSUE TITLE
The name of the project directory is given wrong in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sbdeepu09** [thesauravkarmakar/GitHub101#12]
In the step 3 of how to make a pull request
![rsz_1screenshot_from_2020-10-04_22-21-27](https://user-images.githubusercontent.com/56597366/95021705-3b025d00-0690-11eb-939c-2cdff5558450.png)

**Comment by thesauravkarmakar** [comment]
Okay, go ahead fix this @sbdeepu09
