### ISSUE TITLE
Guide: Cleaning up git repository 

### ISSUE THREAD

**Issue by jikuja** [thesauravkarmakar/GitHub101#16]
I would like to document how to clean git repository after adding .gitignore file and how to recover deleted files from a historical commit.

This is not strictly Github content but tidy repository makes collaboration easier and faster.

**Comment by thesauravkarmakar** [comment]
Assigning it to you @jikuja

**Comment by thesauravkarmakar** [comment]
@jikuja Will, you do it or should I assign it to somebody else?

**Comment by theamritanair** [comment]
@thesauravkarmakar I would like to work on this
