### ISSUE TITLE
Guide: How to make a Pull Request (PR) 

### ISSUE THREAD

**Issue by thesauravkarmakar** [thesauravkarmakar/GitHub101#24]
Create a proper guide for making a Pull Request (PR) in a GitHub repository with screenshots in it. 

_Refer for Format & Style:_ https://github.com/thesauravkarmakar/GitHub101/blob/master/Guides/creating_repo.md

**Comment by dakshayahuja** [comment]
Hey @thesauravkarmakar,
I can make a guide for making a Pull Request as per your format and style.
Please assign it to me.

**Comment by Jackmt9** [comment]
Can I take care of this?

**Comment by thesauravkarmakar** [comment]
Sure @Jackmt9! Follow this style of writing with screenshots https://github.com/thesauravkarmakar/GitHub101/blob/master/Guides/creating_repo.md

**Comment by Jackmt9** [comment]
Thanks @thesauravkarmakar ! I've gone ahead and created a pull request for this file. Sure hope I did the pull request right lol 🙃

**Comment by thesauravkarmakar** [comment]
> Thanks @thesauravkarmakar ! I've gone ahead and created a pull request for this file. Sure hope I did the pull request right lol 🙃

You did! 👍 Don't forget to ⭐ the repo
