### ISSUE TITLE
Guide: Create Your First Issue

### ISSUE THREAD

**Issue by ilhambara** [thesauravkarmakar/GitHub101#31]
I want to make a simple guideline for how to make the first issue for beginners.

It also includes what are milestones, labels, and assignees mean.

**Comment by thesauravkarmakar** [comment]
Assigning it you @ilhambara. Please refer to other [Guides](https://github.com/thesauravkarmakar/GitHub101/tree/master/Guides) format and style

**Comment by ilhambara** [comment]
Thanks. I will work for it

**Comment by thesauravkarmakar** [comment]
Nice work!
