### ISSUE TITLE
Guide : Create Change_GitEditor.md

### ISSUE THREAD

**Issue by ghost** [thesauravkarmakar/GitHub101#37]
hello , I was wondering if I could make a guide to change your git editor .

**Comment by thesauravkarmakar** [comment]
Refer to other [Guides](https://github.com/thesauravkarmakar/GitHub101/tree/master/Guides) format and style

**Comment by thesauravkarmakar** [comment]
@Pandz18 Why did you PR the same for this issue, you should have created another one?

**Comment by ghost** [comment]
Hey , I did it, was it ok ?

**Comment by thesauravkarmakar** [comment]
You did but there are some conflicts in the PR because you tried messed the PR. Remember next time, what I told you!

**Comment by Pandz18** [comment]
I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?

**Comment by thesauravkarmakar** [comment]
> I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?

I have to fix that.

**Comment by ghost** [comment]
> > I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?
> 
> I have to fix that.

Oh , Ok , I so so apologise for the inconvenience , I'm new to Github and I don't know how to clean my files and such , will try to be better next time . Sorry again

**Comment by thesauravkarmakar** [comment]
> > > I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?
> > 
> > 
> > I have to fix that.
> 
> Oh , Ok , I so so apologise for the inconvenience , I'm new to Github and I don't know how to clean my files and such , will try to be better next time . Sorry again

No issue! That's why this repo is being created

**Comment by ghost** [comment]
> > > > I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?
> > > 
> > > 
> > > I have to fix that.
> > 
> > 
> > Oh , Ok , I so so apologise for the inconvenience , I'm new to Github and I don't know how to clean my files and such , will try to be better next time . Sorry again
> 
> No issue! That's why this repo is being created

Thank you so much , I'm happy to be a part of this . Another question , about my guide: to upload a file , so should I add my text in the contributing.md and PR that ?

**Comment by thesauravkarmakar** [comment]
> > > > > I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?
> > > > 
> > > > 
> > > > I have to fix that.
> > > 
> > > 
> > > Oh , Ok , I so so apologise for the inconvenience , I'm new to Github and I don't know how to clean my files and such , will try to be better next time . Sorry again
> > 
> > 
> > No issue! That's why this repo is being created
> 
> Thank you so much , I'm happy to be a part of this . Another question , about my guide: to upload a file , so should I add my text in the contributing.md and PR that ?

No!

**Comment by ghost** [comment]
> > > > > > I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?
> > > > > 
> > > > > 
> > > > > I have to fix that.
> > > > 
> > > > 
> > > > Oh , Ok , I so so apologise for the inconvenience , I'm new to Github and I don't know how to clean my files and such , will try to be better next time . Sorry again
> > > 
> > > 
> > > No issue! That's why this repo is being created
> > 
> > 
> > Thank you so much , I'm happy to be a part of this . Another question , about my guide: to upload a file , so should I add my text in the contributing.md and PR that ?
> 
> No!

I didn't change anything , just one more thing , I did a PR for my git editor change . Also I feel like I'm messing up , I'm so sorry

**Comment by thesauravkarmakar** [comment]
> > > > > > > I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?
> > > > > > 
> > > > > > 
> > > > > > I have to fix that.
> > > > > 
> > > > > 
> > > > > Oh , Ok , I so so apologise for the inconvenience , I'm new to Github and I don't know how to clean my files and such , will try to be better next time . Sorry again
> > > > 
> > > > 
> > > > No issue! That's why this repo is being created
> > > 
> > > 
> > > Thank you so much , I'm happy to be a part of this . Another question , about my guide: to upload a file , so should I add my text in the contributing.md and PR that ?
> > 
> > 
> > No!
> 
> I didn't change anything , just one more thing , I did a PR for my git editor change . Also I feel like I'm messing up , I'm so sorry

I will review that and do things accordingly.

**Comment by ghost** [comment]
> > > > > > > > I will do the necessary changes , I'm sorry if it's a bad question but what specifically should I do ?
> > > > > > > 
> > > > > > > 
> > > > > > > I have to fix that.
> > > > > > 
> > > > > > 
> > > > > > Oh , Ok , I so so apologise for the inconvenience , I'm new to Github and I don't know how to clean my files and such , will try to be better next time . Sorry again
> > > > > 
> > > > > 
> > > > > No issue! That's why this repo is being created
> > > > 
> > > > 
> > > > Thank you so much , I'm happy to be a part of this . Another question , about my guide: to upload a file , so should I add my text in the contributing.md and PR that ?
> > > 
> > > 
> > > No!
> > 
> > 
> > I didn't change anything , just one more thing , I did a PR for my git editor change . Also I feel like I'm messing up , I'm so sorry
> 
> I will review that and do things accordingly.

thank you
