### ISSUE TITLE
create GUIDE : remote_repo.md

### ISSUE THREAD

**Issue by ghost** [thesauravkarmakar/GitHub101#38]
I was wondering if I could make a guide to create a remote repository

**Comment by thesauravkarmakar** [comment]
Okay! Follow the  [Guides](https://github.com/thesauravkarmakar/GitHub101/tree/master/Guides) format and style

**Comment by ghost** [comment]
sure will do , thank you

**Comment by ghost** [comment]
Hey , did you check the PR ? Was it ok ?

**Comment by thesauravkarmakar** [comment]
> Hey , did you check the PR ? Was it ok ?

It was but you didn't put the Guide in the Guides folder. It's okay, I will do the finishing work.

**Comment by ghost** [comment]
oh I apologise for that but thank you
