### ISSUE TITLE
Replacing Screenshots in Guide: Creating a Pull Request (PR) on GitHub

### ISSUE THREAD

**Issue by thesauravkarmakar** [thesauravkarmakar/GitHub101#42]
Adding screenshots of this repo not other repo while documentation

**Comment by POOJAPRABHU450** [comment]
Hi , can you please assign this issue to me??

**Comment by codefunlearn** [comment]
Hi @thesauravkarmakar  . If this is available, I'd like to do it. Thanks!

**Comment by thesauravkarmakar** [comment]
No, it's not available @codefunlearn
