### ISSUE TITLE
Guide: Creating a GitHub Repository 

### ISSUE THREAD

**Issue by thesauravkarmakar** [thesauravkarmakar/GitHub101#7]
Create a proper guide for creating a GitHub repository with screenshots in it.

**Comment by Harshal0506** [comment]
Hey I Can do this :)
Can you assign me this task

**Comment by thesauravkarmakar** [comment]
@Harshal0506 Sure! Share with others also, to give them chance to contribute.

**Comment by Harshal0506** [comment]
@thesauravkarmakar is there any time constraint ? actually I was thinking to work on it after a day or two 
Will it be okay as I need  to **research** some stuff

**Comment by thesauravkarmakar** [comment]
> @thesauravkarmakar is there any time constraint ? actually I was thinking to work on it after a day or two
> Will it be okay as I need to **research** some stuff

Sure! But don't take more time.

**Comment by Harshal0506** [comment]
Do I have to assume the user has no Github account to start with?

**Comment by thesauravkarmakar** [comment]
> Do I have to assume the user has no Github repository to start with?

Yes!

**Comment by Harshal0506** [comment]
sorry, the typo I wanted to ask that do user have a Github account at the start or he has to sign up for one?

**Comment by thesauravkarmakar** [comment]
> sorry, the typo I wanted to ask that do user have a Github account at the start or he has to sign up for one?

The user has a GitHub account.

**Comment by thesauravkarmakar** [comment]
Done #23
