### ISSUE TITLE
Guide: Cloning a GitHub Repository

### ISSUE THREAD

**Issue by thesauravkarmakar** [thesauravkarmakar/GitHub101#9]
Create a proper guide for cloning a GitHub repository with screenshots in it.

**Comment by Harshal0506** [comment]
hey I can do that can you please assign this to me 
This would help me Learning some great  stuff

@thesauravkarmakar 

Thanks

**Comment by vaishnavi-1** [comment]
I can do this, assign me, I would do that for sure.

**Comment by thesauravkarmakar** [comment]
Sure @vaishnavi-1 !

**Comment by Harshal0506** [comment]
@thesauravkarmakar  is there any time constraint ? can I start working on it after a day or so ?
